name: masareefi
description: "Arabic Expense Tracker Application - مصاريفي"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Localization support
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1

  # State management
  flutter_bloc: ^8.1.6

  # Dependency injection
  get_it: ^8.0.3

  # JSON serialization
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0

  # Networking
  dio: ^5.7.0

  # Build system
  build_runner: ^2.4.13

  # Storage
  shared_preferences: ^2.3.4
  flutter_secure_storage: ^9.2.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4

  # Utilities
  url_launcher: ^6.3.1
  persistent_bottom_nav_bar: ^6.2.1
  logger: ^2.5.0
  go_router: ^14.7.1
  package_info_plus: ^8.0.0
  cached_network_image: ^3.2.3
  conditional_builder_null_safety: ^0.0.6
  fluttertoast: ^8.2.2
  sentry_flutter: ^8.3.0
  awesome_dio_interceptor: ^1.2.0
  upgrader: ^10.3.0
  intl: ^0.19.0
  dartz: ^0.10.1
  oktoast: ^3.4.0
  loader_overlay: ^5.0.0
  flutter_spinkit: ^5.2.1
  auto_size_text: ^3.0.0
  awesome_dialog: ^3.2.1
  form_field_validator: ^1.1.0
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/launcher_icon.png
